server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: xq-gateway
zuul:
  routes:
    user:
      path: /user/**
      serviceid: xq-user-service